<div id="product-card" data-productid="{{id}}" class="flex flex-col p-5 gap-5 bg-white w-72 md:w-60 flex-grow-0 shadow-xl transition-all hover:cursor-pointer hover:transition-all hover:border-micromania-blue border-4">
    <div id="product-card" data-productid="{{id}}" class="h-44 flex justify-center items-center">
        <img id="product-card" data-productid="{{id}}" src="./src/assets/{{image}}" alt="{{name}}" class="object-contain h-full">
    </div>
    <div id="product-card" data-productid="{{id}}" class="flex flex-col gap-2">
        <div id="product-card" data-productid="{{id}}" class="flex flex-col gap-2">
            <p id="product-card" data-productid="{{id}}" class="text-micromania-blue text-xl md:text-sm font-semibold">
                {{name}}
            </p>
            <p id="product-card" data-productid="{{id}}" class="text-generic-grey text-xl md:text-sm">
                {{retailer}}
            </p>
        </div>
        <div id="product-card" data-productid="{{id}}" class="flex justify-between items-end">
            <div id="product-buy" data-productid="{{id}}" class="bg-micromania-blue text-white font-medium px-5 py-2 h-fit rounded-lg flex-grow-0 hover:bg-micromania-darkblue">
                Acheter
            </div>
            <div id="product-card" data-productid="{{id}}" class="flex flex-col py-1 gap-4 items-end h-20">
                <div id="product-card" data-productid="{{id}}" class="flex items-end">
                    <p id="product-card" data-productid="{{id}}" class="text-3xl md:text-2xl font-bold">{{price}}</p>
                    <p id="product-card" data-productid="{{id}}" class="text-xl md:text-md font-medium">€</p>
                </div>
            </div>
        </div>
    </div>
</div>