<li id="nav-category" data-categoryid={{id}} class="flex flex-col gap-1 items-center hover:cursor-pointer group">
    <div id="nav-category" data-categoryid={{id}} class="flex w-24 h-24 p-1 rounded-full border-micromania-blue border-4 transition-all group-hover:border-micromania-darkblue">
        <img id="nav-category" data-categoryid={{id}} src="./src/assets/{{image}}" alt="{{name}}" class="w-full h-full object-cover rounded-full border-white border-2 bg-red-500 transition-all group-hover:scale-110">
    </div>
    <p id="nav-category" data-categoryid={{id}} class="text-lg md:text-sm">
        {{name}}
    </p>
</li>