<li class="relative -z-20 flex flex-col gap-1 items-center hover:cursor-pointer">
    <div class="flex w-24 h-24 p-1 rounded-full border-micromania-blue border-4">
        <img src="./src/assets/{{image}}" alt="{{name}}" class="w-full h-full object-cover rounded-full border-white border-2 bg-red-500">
    </div>
    <p class="text-sm">
        {{name}}
    </p>
    <div id="nav-category" data-categoryid={{id}} class="z-0 absolute w-full h-full top-0 left-0"></div>
</li>