<div id="product-card" data-productid="{{id}}" data-optionid="{{id_options}}" class="flex flex-col justify-center items-center gap-1 py-1 px-2 border-transparent border-2 rounded-md hover:cursor-pointer hover:border-micromania-blue hover:border-2">
    <div id="product-card" data-productid="{{id}}" data-optionid="{{id_options}}" class="h-14 w-14 flex justify-center items-center">
        <img id="product-card" data-productid="{{id}}" data-optionid="{{id_options}}" src="./src/assets/{{image}}" alt="{{name}}" class="object-contain h-full">
    </div>
    <p id="product-card" data-productid="{{id}}" data-optionid="{{id_options}}">{{short_name}}</p>
</div>